# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

# container: adoptopenjdk:latest

steps:
  # Java tool installer v0
  # Acquire a specific version of Java from a user-supplied Azure blob or the tool cache and sets JAVA_HOME.
- task: JavaToolInstaller@0
    inputs:
      versionSpec: '11' # string. Required. JDK version. Default: 8.
      jdkArchitectureOption: 'x64' # 'x64' | 'x86'. Required. JDK architecture.
      jdkSourceOption: 'PreInstalled' # 'AzureStorage' | 'LocalDirectory' | 'PreInstalled'. Required. JDK source.
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleBrandVMDevDebug'
  displayName: gradlew assembleBrandVMDevDebug
